name: eshop_b
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.7.0
  injectable: ^2.5.0
  logger: ^2.4.0
  dartz: ^0.10.1
  shared_preferences: ^2.3.2
  equatable: ^2.0.5
  gap: ^3.0.1
  flutter_spinkit: ^5.2.1
  easy_localization: ^3.0.7
  get_it: ^8.0.0
  package_info_plus: ^8.0.2
  firebase_crashlytics: ^4.1.3
  firebase_core: ^3.6.0
  intl: ^0.19.0
  bot_toast: ^4.1.3
  vibration: ^2.0.0
  flutter_bloc: ^8.1.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2

flutter:
  uses-material-design: true
