name: eshop_b
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  gap: ^3.0.1
  get_it: ^7.7.0
  go_router: ^14.2.7
  internet_connection_checker: ^2.0.0
  liquid_pull_to_refresh: ^3.0.1
  quickalert: ^1.1.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/images/
fonts:
  - family: General-reg
    fonts:
      - asset: fonts/GeneralSans-Regular.otf
  - family: General-bold
    fonts:
      - asset: fonts/GeneralSans-Bold.otf
